name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'bluesky_adaptive/**'
      - 'pyproject.toml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Build documentation
        working-directory: docs
        run: |
          make html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/html

      - name: Set env.REPOSITORY_NAME # just the repo, as opposed to org/repo
        run: echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Deploy documentation to blueskyproject.io.
        if: github.repository_owner == 'bluesky' && github.ref_name == 'main'
        # We pin to the SHA, not the tag, for security reasons.
        # https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/security-hardening-for-github-actions#using-third-party-actions
        uses: peaceiris/actions-gh-pages@bbdfb200618d235585ad98e965f4aafc39b4c501 # v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DOCUMENTATION_DEPLOY_KEY }}
          publish_branch: master
          publish_dir: build/html
          external_repository: bluesky/bluesky.github.io
          destination_dir: ${{ env.REPOSITORY_NAME }} # just the repo name, without the "bluesky/"
          keep_files: true # Keep old files.
          force_orphan: false # Keep git history.
